### ISSUE TITLE
Workflow timers should survive restarts

### ISSUE THREAD

**Issue by abesto** [prezi/pasha#20]
As in, workflow state should be stored in the brain, instead of in-process timers. Maybe there's a library that uses a Redis backend with an API similar to `setTimeout` / `setInterval`?

**Comment by abesto** [comment]
After ~10 minutes of search, all libraries I provide too much abstraction (queues etc), except for https://github.com/Woorank/redis-setinterval, which provides only `setInterval` and not `setTimeout`. Currently I feel a custom implementation will be the cleanest and easiest to maintain (something along the lines of "check every minute to see if we need to do something, store the somethings in Redis in a robust way")

**Comment by kbence** [comment]
I'd go with custom implementation as well, it doesn't seem to be complex enough to rely on 3rd party libs that are not designed for this simple use case.

**Comment by davidguerreroprezi** [comment]
This issue has been moved to JIRA (INFRA-1129)
