### ISSUE TITLE
Remove "hipchat" and "pasha" mentions

### ISSUE THREAD

**Issue by balazsdano** [prezi/pasha#6]
Examples:
https://github.com/prezi/pasha/blob/dcc8659f0daef25842105f1793f436e6852a29b3/test/pasha_changelog_test.coffee#L18
https://github.com/prezi/pasha/blob/dcc8659f0daef25842105f1793f436e6852a29b3/pasha_modules/scribe_log.coffee#L24

**Comment by davidguerreroprezi** [comment]
This issue was moved to JIRA: https://prezidoc.atlassian.net/browse/INFRA-1126
