### ISSUE TITLE
do not alert on all prio1 mentions

### ISSUE THREAD

**Issue by szaboat** [prezi/pasha#8]
![screen shot 2015-02-03 at 3 40 01 pm](https://cloud.githubusercontent.com/assets/57303/6022126/f3fd1fc0-abba-11e4-8818-d45b2cc86c3c.png)

**Comment by abesto** [comment]
What would be a good approach? Say, responding only once in a minute? Or smarter heuristics?

**Comment by davidguerreroprezi** [comment]
This issue has been moved to JIRA: https://prezidoc.atlassian.net/browse/INFRA-1127
